# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'angle_detection_ui_2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1711, 907)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.ButtonLine = QtGui.QGroupBox(self.centralwidget)
        self.ButtonLine.setGeometry(QtCore.QRect(0, 0, 811, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ButtonLine.sizePolicy().hasHeightForWidth())
        self.ButtonLine.setSizePolicy(sizePolicy)
        self.ButtonLine.setTitle(_fromUtf8(""))
        self.ButtonLine.setObjectName(_fromUtf8("ButtonLine"))
        self.layoutWidget = QtGui.QWidget(self.ButtonLine)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 290, 51))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.CameraButton_1 = QtGui.QToolButton(self.layoutWidget)
        self.CameraButton_1.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/camera.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CameraButton_1.setIcon(icon)
        self.CameraButton_1.setIconSize(QtCore.QSize(36, 36))
        self.CameraButton_1.setObjectName(_fromUtf8("CameraButton_1"))
        self.horizontalLayout.addWidget(self.CameraButton_1)
        self.CameraButton_2 = QtGui.QToolButton(self.layoutWidget)
        self.CameraButton_2.setText(_fromUtf8(""))
        self.CameraButton_2.setIcon(icon)
        self.CameraButton_2.setIconSize(QtCore.QSize(36, 36))
        self.CameraButton_2.setObjectName(_fromUtf8("CameraButton_2"))
        self.horizontalLayout.addWidget(self.CameraButton_2)
        self.Image = QtGui.QToolButton(self.layoutWidget)
        self.Image.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/images.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Image.setIcon(icon1)
        self.Image.setIconSize(QtCore.QSize(36, 36))
        self.Image.setObjectName(_fromUtf8("Image"))
        self.horizontalLayout.addWidget(self.Image)
        self.Image_List = QtGui.QToolButton(self.layoutWidget)
        self.Image_List.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/image_list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Image_List.setIcon(icon2)
        self.Image_List.setIconSize(QtCore.QSize(36, 36))
        self.Image_List.setObjectName(_fromUtf8("Image_List"))
        self.horizontalLayout.addWidget(self.Image_List)
        self.Run = QtGui.QToolButton(self.layoutWidget)
        self.Run.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Run.setIcon(icon3)
        self.Run.setIconSize(QtCore.QSize(36, 36))
        self.Run.setObjectName(_fromUtf8("Run"))
        self.horizontalLayout.addWidget(self.Run)
        self.Stop = QtGui.QToolButton(self.layoutWidget)
        self.Stop.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Stop.setIcon(icon4)
        self.Stop.setIconSize(QtCore.QSize(36, 36))
        self.Stop.setObjectName(_fromUtf8("Stop"))
        self.horizontalLayout.addWidget(self.Stop)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 60, 911, 651))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.image_window = QtGui.QLabel(self.tab)
        self.image_window.setGeometry(QtCore.QRect(510, 0, 400, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_window.sizePolicy().hasHeightForWidth())
        self.image_window.setSizePolicy(sizePolicy)
        self.image_window.setStyleSheet(_fromUtf8("background-color: rgb(130, 130, 130);"))
        self.image_window.setText(_fromUtf8(""))
        self.image_window.setObjectName(_fromUtf8("image_window"))
        self.warning_window = QtGui.QTextEdit(self.tab)
        self.warning_window.setGeometry(QtCore.QRect(510, 300, 401, 331))
        self.warning_window.setObjectName(_fromUtf8("warning_window"))
        self.graphicsView = QtGui.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 511, 631))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(490, 580, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.tab_3)
        self.dateTimeEdit.setGeometry(QtCore.QRect(290, 580, 194, 22))
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(710, 580, 81, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.tab_3)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(510, 580, 194, 22))
        self.dateTimeEdit_2.setObjectName(_fromUtf8("dateTimeEdit_2"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tabWidget.raise_()
        self.ButtonLine.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1711, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_tool = QtGui.QMenu(self.menubar)
        self.menu_tool.setObjectName(_fromUtf8("menu_tool"))
        self.menu_win = QtGui.QMenu(self.menubar)
        self.menu_win.setObjectName(_fromUtf8("menu_win"))
        self.menu_setting = QtGui.QMenu(self.menubar)
        self.menu_setting.setObjectName(_fromUtf8("menu_setting"))
        self.menu_run = QtGui.QMenu(self.menubar)
        self.menu_run.setObjectName(_fromUtf8("menu_run"))
        self.menu_edit = QtGui.QMenu(self.menubar)
        self.menu_edit.setObjectName(_fromUtf8("menu_edit"))
        self.menu_view = QtGui.QMenu(self.menubar)
        self.menu_view.setObjectName(_fromUtf8("menu_view"))
        self.menu_analyse = QtGui.QMenu(self.menubar)
        self.menu_analyse.setObjectName(_fromUtf8("menu_analyse"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_openfile = QtGui.QAction(MainWindow)
        self.action_openfile.setObjectName(_fromUtf8("action_openfile"))
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.menu_file.addAction(self.action_openfile)
        self.menu_file.addAction(self.action_exit)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_tool.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_win.menuAction())
        self.menubar.addAction(self.menu_setting.menuAction())
        self.menubar.addAction(self.menu_run.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_analyse.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "主界面", None))
        self.label.setText(_translate("MainWindow", "到", None))
        self.pushButton.setText(_translate("MainWindow", "警报信息导出", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "警报界面", None))
        self.menu_file.setTitle(_translate("MainWindow", "文件(F)", None))
        self.menu_tool.setTitle(_translate("MainWindow", "工具(T)", None))
        self.menu_win.setTitle(_translate("MainWindow", "窗口(W)", None))
        self.menu_setting.setTitle(_translate("MainWindow", "设置(S)", None))
        self.menu_run.setTitle(_translate("MainWindow", "运行(R)", None))
        self.menu_edit.setTitle(_translate("MainWindow", "编辑(E)", None))
        self.menu_view.setTitle(_translate("MainWindow", "查看(V)", None))
        self.menu_analyse.setTitle(_translate("MainWindow", "分析(A)", None))
        self.menu_help.setTitle(_translate("MainWindow", "帮助(H)", None))
        self.action_openfile.setText(_translate("MainWindow", "打开(O)", None))
        self.action_exit.setText(_translate("MainWindow", "退出(E)", None))

