# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'angle_detection_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1711, 907)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.ButtonLine = QtGui.QGroupBox(self.centralwidget)
        self.ButtonLine.setGeometry(QtCore.QRect(0, 0, 741, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ButtonLine.sizePolicy().hasHeightForWidth())
        self.ButtonLine.setSizePolicy(sizePolicy)
        self.ButtonLine.setTitle(_fromUtf8(""))
        self.ButtonLine.setObjectName(_fromUtf8("ButtonLine"))
        self.layoutWidget = QtGui.QWidget(self.ButtonLine)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 295, 51))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.CameraButton_1 = QtGui.QToolButton(self.layoutWidget)
        self.CameraButton_1.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/camera.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CameraButton_1.setIcon(icon)
        self.CameraButton_1.setIconSize(QtCore.QSize(36, 36))
        self.CameraButton_1.setObjectName(_fromUtf8("CameraButton_1"))
        self.horizontalLayout.addWidget(self.CameraButton_1)
        self.CameraButton_2 = QtGui.QToolButton(self.layoutWidget)
        self.CameraButton_2.setText(_fromUtf8(""))
        self.CameraButton_2.setIcon(icon)
        self.CameraButton_2.setIconSize(QtCore.QSize(36, 36))
        self.CameraButton_2.setObjectName(_fromUtf8("CameraButton_2"))
        self.horizontalLayout.addWidget(self.CameraButton_2)
        self.Image = QtGui.QToolButton(self.layoutWidget)
        self.Image.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/images.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Image.setIcon(icon1)
        self.Image.setIconSize(QtCore.QSize(36, 36))
        self.Image.setObjectName(_fromUtf8("Image"))
        self.horizontalLayout.addWidget(self.Image)
        self.Image_List = QtGui.QToolButton(self.layoutWidget)
        self.Image_List.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/image_list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Image_List.setIcon(icon2)
        self.Image_List.setIconSize(QtCore.QSize(36, 36))
        self.Image_List.setObjectName(_fromUtf8("Image_List"))
        self.horizontalLayout.addWidget(self.Image_List)
        self.Run = QtGui.QPushButton(self.layoutWidget)
        self.Run.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Run.setIcon(icon3)
        self.Run.setIconSize(QtCore.QSize(36, 36))
        self.Run.setObjectName(_fromUtf8("Run"))
        self.horizontalLayout.addWidget(self.Run)
        self.Stop = QtGui.QToolButton(self.layoutWidget)
        self.Stop.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Stop.setIcon(icon4)
        self.Stop.setIconSize(QtCore.QSize(36, 36))
        self.Stop.setObjectName(_fromUtf8("Stop"))
        self.horizontalLayout.addWidget(self.Stop)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 676, 441))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(1, -1, -1, 1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.listWidget = QtGui.QListWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/lenovo/.designer/backup/icon/detection.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/lenovo/.designer/backup/icon/measure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/lenovo/.designer/backup/icon/location.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/lenovo/.designer/backup/icon/recognition.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.listWidget.addItem(item)
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.operateInstruction = QtGui.QTextBrowser(self.layoutWidget1)
        self.operateInstruction.setObjectName(_fromUtf8("operateInstruction"))
        self.gridLayout_2.addWidget(self.operateInstruction, 2, 1, 1, 1)
        self.image_window = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_window.sizePolicy().hasHeightForWidth())
        self.image_window.setSizePolicy(sizePolicy)
        self.image_window.setText(_fromUtf8(""))
        self.image_window.setObjectName(_fromUtf8("image_window"))
        self.gridLayout_2.addWidget(self.image_window, 0, 1, 2, 1)
        self.treeWidget = QtGui.QTreeWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.gridLayout_2.addWidget(self.treeWidget, 1, 0, 2, 1)
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.layoutWidget2 = QtGui.QWidget(self.tab1)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 197, 226))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_2)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBox)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_3)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_4)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_14 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_14)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_5)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_13 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.comboBox = QtGui.QComboBox(self.layoutWidget2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.comboBox)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 241, 192))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 1, item)
        self.gridLayoutWidget = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 230, 176, 101))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 2, 3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1711, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_tool = QtGui.QMenu(self.menubar)
        self.menu_tool.setObjectName(_fromUtf8("menu_tool"))
        self.menu_win = QtGui.QMenu(self.menubar)
        self.menu_win.setObjectName(_fromUtf8("menu_win"))
        self.menu_setting = QtGui.QMenu(self.menubar)
        self.menu_setting.setObjectName(_fromUtf8("menu_setting"))
        self.menu_run = QtGui.QMenu(self.menubar)
        self.menu_run.setObjectName(_fromUtf8("menu_run"))
        self.menu_edit = QtGui.QMenu(self.menubar)
        self.menu_edit.setObjectName(_fromUtf8("menu_edit"))
        self.menu_view = QtGui.QMenu(self.menubar)
        self.menu_view.setObjectName(_fromUtf8("menu_view"))
        self.menu_analyse = QtGui.QMenu(self.menubar)
        self.menu_analyse.setObjectName(_fromUtf8("menu_analyse"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_openfile = QtGui.QAction(MainWindow)
        self.action_openfile.setObjectName(_fromUtf8("action_openfile"))
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.menu_file.addAction(self.action_openfile)
        self.menu_file.addAction(self.action_exit)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_tool.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_win.menuAction())
        self.menubar.addAction(self.menu_setting.menuAction())
        self.menubar.addAction(self.menu_run.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_analyse.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "检测", None))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "测量", None))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "定位", None))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "识别", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.operateInstruction.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">操作说明：</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1.选择检测相机</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2.设定目标检测区域</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3.选择检测工件类型</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">4.点击运行</span></p></body></html>", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "检测选项", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "缺陷检测", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "型号1", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "型号2", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "数量检测", None))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "型号1", None))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "型号2", None))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "智能检测", None))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "型号1", None))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "型号2", None))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "色彩检测", None))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "型号1", None))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "型号2", None))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "有无检测", None))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "型号1", None))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "型号2", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "目标区域参数：", None))
        self.label_3.setText(_translate("MainWindow", "   X轴起始坐标：", None))
        self.label_4.setText(_translate("MainWindow", "   X轴结束坐标：", None))
        self.label_6.setText(_translate("MainWindow", "   Y轴起始坐标：", None))
        self.label_5.setText(_translate("MainWindow", "   X轴中点坐标：", None))
        self.label_14.setText(_translate("MainWindow", "   Y轴结束坐标：", None))
        self.label_13.setText(_translate("MainWindow", "待检测工件类型：", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "VUM30", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "VUM40", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "VUM50", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "参数设定", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "角度1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "角度2", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "类型", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "角度", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "角度检测", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "89.83", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "角度检测", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "89.71", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("MainWindow", "合格数", None))
        self.label_9.setText(_translate("MainWindow", "合格率", None))
        self.label_7.setText(_translate("MainWindow", "总数", None))
        self.label_10.setText(_translate("MainWindow", "- -", None))
        self.label_11.setText(_translate("MainWindow", "- -", None))
        self.label_12.setText(_translate("MainWindow", "- -", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "输出结果", None))
        self.menu_file.setTitle(_translate("MainWindow", "文件(F)", None))
        self.menu_tool.setTitle(_translate("MainWindow", "工具(T)", None))
        self.menu_win.setTitle(_translate("MainWindow", "窗口(W)", None))
        self.menu_setting.setTitle(_translate("MainWindow", "设置(S)", None))
        self.menu_run.setTitle(_translate("MainWindow", "运行(R)", None))
        self.menu_edit.setTitle(_translate("MainWindow", "编辑(E)", None))
        self.menu_view.setTitle(_translate("MainWindow", "查看(V)", None))
        self.menu_analyse.setTitle(_translate("MainWindow", "分析(A)", None))
        self.menu_help.setTitle(_translate("MainWindow", "帮助(H)", None))
        self.action_openfile.setText(_translate("MainWindow", "打开(O)", None))
        self.action_exit.setText(_translate("MainWindow", "退出(E)", None))

