# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from Paint3 import draw
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import *
from getdata import BackendThread

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1920, 1072)
        MainWindow.setStyleSheet(";\n"
                                 "font: 13pt \"微软雅黑\";\n"
                                 "color: rgb(60, 60, 60);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = draw(self.centralwidget)
        #self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(14, 160, 1631, 160))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, -1, -1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.action = QtWidgets.QLabel(self.widget)
        self.action.setAutoFillBackground(False)
        self.action.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.action.setFrameShape(QtWidgets.QFrame.Box)
        self.action.setFrameShadow(QtWidgets.QFrame.Plain)
        self.action.setLineWidth(1)
        self.action.setMidLineWidth(0)
        self.action.setObjectName("action")
        self.gridLayout.addWidget(self.action, 2, 0, 1, 1)
        self.carFault1 = QtWidgets.QLabel(self.widget)
        self.carFault1.setAutoFillBackground(False)
        self.carFault1.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carFault1.setFrameShape(QtWidgets.QFrame.Box)
        self.carFault1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carFault1.setLineWidth(1)
        self.carFault1.setMidLineWidth(0)
        self.carFault1.setObjectName("carFault1")
        self.gridLayout.addWidget(self.carFault1, 5, 1, 1, 1)
        self.carAction1 = QtWidgets.QLabel(self.widget)
        self.carAction1.setAutoFillBackground(False)
        self.carAction1.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carAction1.setFrameShape(QtWidgets.QFrame.Box)
        self.carAction1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carAction1.setLineWidth(1)
        self.carAction1.setMidLineWidth(0)
        self.carAction1.setObjectName("carAction1")
        self.gridLayout.addWidget(self.carAction1, 2, 1, 1, 1)
        self.fault = QtWidgets.QLabel(self.widget)
        self.fault.setAutoFillBackground(False)
        self.fault.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.fault.setFrameShape(QtWidgets.QFrame.Box)
        self.fault.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fault.setLineWidth(1)
        self.fault.setMidLineWidth(0)
        self.fault.setObjectName("fault")
        self.gridLayout.addWidget(self.fault, 5, 0, 1, 1)
        self.carDest1 = QtWidgets.QLabel(self.widget)
        self.carDest1.setAutoFillBackground(False)
        self.carDest1.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carDest1.setFrameShape(QtWidgets.QFrame.Box)
        self.carDest1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carDest1.setLineWidth(1)
        self.carDest1.setMidLineWidth(0)
        self.carDest1.setObjectName("carDest1")
        self.gridLayout.addWidget(self.carDest1, 1, 1, 1, 1)
        self.carGoods1 = QtWidgets.QLabel(self.widget)
        self.carGoods1.setAutoFillBackground(False)
        self.carGoods1.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carGoods1.setFrameShape(QtWidgets.QFrame.Box)
        self.carGoods1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carGoods1.setLineWidth(1)
        self.carGoods1.setMidLineWidth(0)
        self.carGoods1.setObjectName("carGoods1")
        self.gridLayout.addWidget(self.carGoods1, 4, 1, 1, 1)
        self.start = QtWidgets.QLabel(self.widget)
        self.start.setAutoFillBackground(False)
        self.start.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.start.setFrameShape(QtWidgets.QFrame.Box)
        self.start.setFrameShadow(QtWidgets.QFrame.Plain)
        self.start.setLineWidth(1)
        self.start.setMidLineWidth(0)
        self.start.setObjectName("start")
        self.gridLayout.addWidget(self.start, 0, 0, 1, 1)
        self.carBattery1 = QtWidgets.QLabel(self.widget)
        self.carBattery1.setAutoFillBackground(False)
        self.carBattery1.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carBattery1.setFrameShape(QtWidgets.QFrame.Box)
        self.carBattery1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carBattery1.setLineWidth(1)
        self.carBattery1.setMidLineWidth(0)
        self.carBattery1.setObjectName("carBattery1")
        self.gridLayout.addWidget(self.carBattery1, 3, 1, 1, 1)
        self.goods = QtWidgets.QLabel(self.widget)
        self.goods.setAutoFillBackground(False)
        self.goods.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.goods.setFrameShape(QtWidgets.QFrame.Box)
        self.goods.setFrameShadow(QtWidgets.QFrame.Plain)
        self.goods.setLineWidth(1)
        self.goods.setMidLineWidth(0)
        self.goods.setObjectName("goods")
        self.gridLayout.addWidget(self.goods, 4, 0, 1, 1)
        self.dest = QtWidgets.QLabel(self.widget)
        self.dest.setAutoFillBackground(False)
        self.dest.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.dest.setFrameShape(QtWidgets.QFrame.Box)
        self.dest.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dest.setLineWidth(1)
        self.dest.setMidLineWidth(0)
        self.dest.setObjectName("dest")
        self.gridLayout.addWidget(self.dest, 1, 0, 1, 1)
        self.battery = QtWidgets.QLabel(self.widget)
        self.battery.setAutoFillBackground(False)
        self.battery.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.battery.setFrameShape(QtWidgets.QFrame.Box)
        self.battery.setFrameShadow(QtWidgets.QFrame.Plain)
        self.battery.setLineWidth(1)
        self.battery.setMidLineWidth(0)
        self.battery.setObjectName("battery")
        self.gridLayout.addWidget(self.battery, 3, 0, 1, 1)
        self.carStart1 = QtWidgets.QLabel(self.widget)
        self.carStart1.setAutoFillBackground(False)
        self.carStart1.setStyleSheet("")
        self.carStart1.setFrameShape(QtWidgets.QFrame.Box)
        self.carStart1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carStart1.setLineWidth(1)
        self.carStart1.setMidLineWidth(0)
        self.carStart1.setObjectName("carStart1")
        self.gridLayout.addWidget(self.carStart1, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.action_2 = QtWidgets.QLabel(self.widget)
        self.action_2.setAutoFillBackground(False)
        self.action_2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.action_2.setFrameShape(QtWidgets.QFrame.Box)
        self.action_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.action_2.setLineWidth(1)
        self.action_2.setMidLineWidth(0)
        self.action_2.setObjectName("action_2")
        self.gridLayout_2.addWidget(self.action_2, 2, 0, 1, 1)
        self.carFault2 = QtWidgets.QLabel(self.widget)
        self.carFault2.setAutoFillBackground(False)
        self.carFault2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carFault2.setFrameShape(QtWidgets.QFrame.Box)
        self.carFault2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carFault2.setLineWidth(1)
        self.carFault2.setMidLineWidth(0)
        self.carFault2.setObjectName("carFault2")
        self.gridLayout_2.addWidget(self.carFault2, 5, 1, 1, 1)
        self.carAction2 = QtWidgets.QLabel(self.widget)
        self.carAction2.setAutoFillBackground(False)
        self.carAction2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carAction2.setFrameShape(QtWidgets.QFrame.Box)
        self.carAction2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carAction2.setLineWidth(1)
        self.carAction2.setMidLineWidth(0)
        self.carAction2.setObjectName("carAction2")
        self.gridLayout_2.addWidget(self.carAction2, 2, 1, 1, 1)
        self.fault_2 = QtWidgets.QLabel(self.widget)
        self.fault_2.setAutoFillBackground(False)
        self.fault_2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.fault_2.setFrameShape(QtWidgets.QFrame.Box)
        self.fault_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fault_2.setLineWidth(1)
        self.fault_2.setMidLineWidth(0)
        self.fault_2.setObjectName("fault_2")
        self.gridLayout_2.addWidget(self.fault_2, 5, 0, 1, 1)
        self.carDest2 = QtWidgets.QLabel(self.widget)
        self.carDest2.setAutoFillBackground(False)
        self.carDest2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carDest2.setFrameShape(QtWidgets.QFrame.Box)
        self.carDest2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carDest2.setLineWidth(1)
        self.carDest2.setMidLineWidth(0)
        self.carDest2.setObjectName("carDest2")
        self.gridLayout_2.addWidget(self.carDest2, 1, 1, 1, 1)
        self.carGoods2 = QtWidgets.QLabel(self.widget)
        self.carGoods2.setAutoFillBackground(False)
        self.carGoods2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carGoods2.setFrameShape(QtWidgets.QFrame.Box)
        self.carGoods2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carGoods2.setLineWidth(1)
        self.carGoods2.setMidLineWidth(0)
        self.carGoods2.setObjectName("carGoods2")
        self.gridLayout_2.addWidget(self.carGoods2, 4, 1, 1, 1)
        self.start_2 = QtWidgets.QLabel(self.widget)
        self.start_2.setAutoFillBackground(False)
        self.start_2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.start_2.setFrameShape(QtWidgets.QFrame.Box)
        self.start_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.start_2.setLineWidth(1)
        self.start_2.setMidLineWidth(0)
        self.start_2.setObjectName("start_2")
        self.gridLayout_2.addWidget(self.start_2, 0, 0, 1, 1)
        self.carBattery2 = QtWidgets.QLabel(self.widget)
        self.carBattery2.setAutoFillBackground(False)
        self.carBattery2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carBattery2.setFrameShape(QtWidgets.QFrame.Box)
        self.carBattery2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carBattery2.setLineWidth(1)
        self.carBattery2.setMidLineWidth(0)
        self.carBattery2.setObjectName("carBattery2")
        self.gridLayout_2.addWidget(self.carBattery2, 3, 1, 1, 1)
        self.goods_2 = QtWidgets.QLabel(self.widget)
        self.goods_2.setAutoFillBackground(False)
        self.goods_2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.goods_2.setFrameShape(QtWidgets.QFrame.Box)
        self.goods_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.goods_2.setLineWidth(1)
        self.goods_2.setMidLineWidth(0)
        self.goods_2.setObjectName("goods_2")
        self.gridLayout_2.addWidget(self.goods_2, 4, 0, 1, 1)
        self.dest_2 = QtWidgets.QLabel(self.widget)
        self.dest_2.setAutoFillBackground(False)
        self.dest_2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.dest_2.setFrameShape(QtWidgets.QFrame.Box)
        self.dest_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dest_2.setLineWidth(1)
        self.dest_2.setMidLineWidth(0)
        self.dest_2.setObjectName("dest_2")
        self.gridLayout_2.addWidget(self.dest_2, 1, 0, 1, 1)
        self.battery_2 = QtWidgets.QLabel(self.widget)
        self.battery_2.setAutoFillBackground(False)
        self.battery_2.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.battery_2.setFrameShape(QtWidgets.QFrame.Box)
        self.battery_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.battery_2.setLineWidth(1)
        self.battery_2.setMidLineWidth(0)
        self.battery_2.setObjectName("battery_2")
        self.gridLayout_2.addWidget(self.battery_2, 3, 0, 1, 1)
        self.carStart2 = QtWidgets.QLabel(self.widget)
        self.carStart2.setAutoFillBackground(False)
        self.carStart2.setStyleSheet("")
        self.carStart2.setFrameShape(QtWidgets.QFrame.Box)
        self.carStart2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carStart2.setLineWidth(1)
        self.carStart2.setMidLineWidth(0)
        self.carStart2.setObjectName("carStart2")
        self.gridLayout_2.addWidget(self.carStart2, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.action_3 = QtWidgets.QLabel(self.widget)
        self.action_3.setAutoFillBackground(False)
        self.action_3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.action_3.setFrameShape(QtWidgets.QFrame.Box)
        self.action_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.action_3.setLineWidth(1)
        self.action_3.setMidLineWidth(0)
        self.action_3.setObjectName("action_3")
        self.gridLayout_3.addWidget(self.action_3, 2, 0, 1, 1)
        self.carFault3 = QtWidgets.QLabel(self.widget)
        self.carFault3.setAutoFillBackground(False)
        self.carFault3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carFault3.setFrameShape(QtWidgets.QFrame.Box)
        self.carFault3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carFault3.setLineWidth(1)
        self.carFault3.setMidLineWidth(0)
        self.carFault3.setObjectName("carFault3")
        self.gridLayout_3.addWidget(self.carFault3, 5, 1, 1, 1)
        self.carAction3 = QtWidgets.QLabel(self.widget)
        self.carAction3.setAutoFillBackground(False)
        self.carAction3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carAction3.setFrameShape(QtWidgets.QFrame.Box)
        self.carAction3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carAction3.setLineWidth(1)
        self.carAction3.setMidLineWidth(0)
        self.carAction3.setObjectName("carAction3")
        self.gridLayout_3.addWidget(self.carAction3, 2, 1, 1, 1)
        self.fault_3 = QtWidgets.QLabel(self.widget)
        self.fault_3.setAutoFillBackground(False)
        self.fault_3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.fault_3.setFrameShape(QtWidgets.QFrame.Box)
        self.fault_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fault_3.setLineWidth(1)
        self.fault_3.setMidLineWidth(0)
        self.fault_3.setObjectName("fault_3")
        self.gridLayout_3.addWidget(self.fault_3, 5, 0, 1, 1)
        self.carDest3 = QtWidgets.QLabel(self.widget)
        self.carDest3.setAutoFillBackground(False)
        self.carDest3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carDest3.setFrameShape(QtWidgets.QFrame.Box)
        self.carDest3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carDest3.setLineWidth(1)
        self.carDest3.setMidLineWidth(0)
        self.carDest3.setObjectName("carDest3")
        self.gridLayout_3.addWidget(self.carDest3, 1, 1, 1, 1)
        self.carGoods3 = QtWidgets.QLabel(self.widget)
        self.carGoods3.setAutoFillBackground(False)
        self.carGoods3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carGoods3.setFrameShape(QtWidgets.QFrame.Box)
        self.carGoods3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carGoods3.setLineWidth(1)
        self.carGoods3.setMidLineWidth(0)
        self.carGoods3.setObjectName("carGoods3")
        self.gridLayout_3.addWidget(self.carGoods3, 4, 1, 1, 1)
        self.start_3 = QtWidgets.QLabel(self.widget)
        self.start_3.setAutoFillBackground(False)
        self.start_3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.start_3.setFrameShape(QtWidgets.QFrame.Box)
        self.start_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.start_3.setLineWidth(1)
        self.start_3.setMidLineWidth(0)
        self.start_3.setObjectName("start_3")
        self.gridLayout_3.addWidget(self.start_3, 0, 0, 1, 1)
        self.carBattery3 = QtWidgets.QLabel(self.widget)
        self.carBattery3.setAutoFillBackground(False)
        self.carBattery3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carBattery3.setFrameShape(QtWidgets.QFrame.Box)
        self.carBattery3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carBattery3.setLineWidth(1)
        self.carBattery3.setMidLineWidth(0)
        self.carBattery3.setObjectName("carBattery3")
        self.gridLayout_3.addWidget(self.carBattery3, 3, 1, 1, 1)
        self.goods_3 = QtWidgets.QLabel(self.widget)
        self.goods_3.setAutoFillBackground(False)
        self.goods_3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.goods_3.setFrameShape(QtWidgets.QFrame.Box)
        self.goods_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.goods_3.setLineWidth(1)
        self.goods_3.setMidLineWidth(0)
        self.goods_3.setObjectName("goods_3")
        self.gridLayout_3.addWidget(self.goods_3, 4, 0, 1, 1)
        self.dest_3 = QtWidgets.QLabel(self.widget)
        self.dest_3.setAutoFillBackground(False)
        self.dest_3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.dest_3.setFrameShape(QtWidgets.QFrame.Box)
        self.dest_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dest_3.setLineWidth(1)
        self.dest_3.setMidLineWidth(0)
        self.dest_3.setObjectName("dest_3")
        self.gridLayout_3.addWidget(self.dest_3, 1, 0, 1, 1)
        self.battery_3 = QtWidgets.QLabel(self.widget)
        self.battery_3.setAutoFillBackground(False)
        self.battery_3.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.battery_3.setFrameShape(QtWidgets.QFrame.Box)
        self.battery_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.battery_3.setLineWidth(1)
        self.battery_3.setMidLineWidth(0)
        self.battery_3.setObjectName("battery_3")
        self.gridLayout_3.addWidget(self.battery_3, 3, 0, 1, 1)
        self.carStart3 = QtWidgets.QLabel(self.widget)
        self.carStart3.setAutoFillBackground(False)
        self.carStart3.setStyleSheet("")
        self.carStart3.setFrameShape(QtWidgets.QFrame.Box)
        self.carStart3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carStart3.setLineWidth(1)
        self.carStart3.setMidLineWidth(0)
        self.carStart3.setObjectName("carStart3")
        self.gridLayout_3.addWidget(self.carStart3, 0, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.action_4 = QtWidgets.QLabel(self.widget)
        self.action_4.setAutoFillBackground(False)
        self.action_4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.action_4.setFrameShape(QtWidgets.QFrame.Box)
        self.action_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.action_4.setLineWidth(1)
        self.action_4.setMidLineWidth(0)
        self.action_4.setObjectName("action_4")
        self.gridLayout_4.addWidget(self.action_4, 2, 0, 1, 1)
        self.carFault4 = QtWidgets.QLabel(self.widget)
        self.carFault4.setAutoFillBackground(False)
        self.carFault4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carFault4.setFrameShape(QtWidgets.QFrame.Box)
        self.carFault4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carFault4.setLineWidth(1)
        self.carFault4.setMidLineWidth(0)
        self.carFault4.setObjectName("carFault4")
        self.gridLayout_4.addWidget(self.carFault4, 5, 1, 1, 1)
        self.carAction4 = QtWidgets.QLabel(self.widget)
        self.carAction4.setAutoFillBackground(False)
        self.carAction4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carAction4.setFrameShape(QtWidgets.QFrame.Box)
        self.carAction4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carAction4.setLineWidth(1)
        self.carAction4.setMidLineWidth(0)
        self.carAction4.setObjectName("carAction4")
        self.gridLayout_4.addWidget(self.carAction4, 2, 1, 1, 1)
        self.fault_4 = QtWidgets.QLabel(self.widget)
        self.fault_4.setAutoFillBackground(False)
        self.fault_4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.fault_4.setFrameShape(QtWidgets.QFrame.Box)
        self.fault_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fault_4.setLineWidth(1)
        self.fault_4.setMidLineWidth(0)
        self.fault_4.setObjectName("fault_4")
        self.gridLayout_4.addWidget(self.fault_4, 5, 0, 1, 1)
        self.carDest4 = QtWidgets.QLabel(self.widget)
        self.carDest4.setAutoFillBackground(False)
        self.carDest4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carDest4.setFrameShape(QtWidgets.QFrame.Box)
        self.carDest4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carDest4.setLineWidth(1)
        self.carDest4.setMidLineWidth(0)
        self.carDest4.setObjectName("carDest4")
        self.gridLayout_4.addWidget(self.carDest4, 1, 1, 1, 1)
        self.carGoods4 = QtWidgets.QLabel(self.widget)
        self.carGoods4.setAutoFillBackground(False)
        self.carGoods4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carGoods4.setFrameShape(QtWidgets.QFrame.Box)
        self.carGoods4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carGoods4.setLineWidth(1)
        self.carGoods4.setMidLineWidth(0)
        self.carGoods4.setObjectName("carGoods4")
        self.gridLayout_4.addWidget(self.carGoods4, 4, 1, 1, 1)
        self.start_4 = QtWidgets.QLabel(self.widget)
        self.start_4.setAutoFillBackground(False)
        self.start_4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.start_4.setFrameShape(QtWidgets.QFrame.Box)
        self.start_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.start_4.setLineWidth(1)
        self.start_4.setMidLineWidth(0)
        self.start_4.setObjectName("start_4")
        self.gridLayout_4.addWidget(self.start_4, 0, 0, 1, 1)
        self.carBattery4 = QtWidgets.QLabel(self.widget)
        self.carBattery4.setAutoFillBackground(False)
        self.carBattery4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carBattery4.setFrameShape(QtWidgets.QFrame.Box)
        self.carBattery4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carBattery4.setLineWidth(1)
        self.carBattery4.setMidLineWidth(0)
        self.carBattery4.setObjectName("carBattery4")
        self.gridLayout_4.addWidget(self.carBattery4, 3, 1, 1, 1)
        self.goods_4 = QtWidgets.QLabel(self.widget)
        self.goods_4.setAutoFillBackground(False)
        self.goods_4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.goods_4.setFrameShape(QtWidgets.QFrame.Box)
        self.goods_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.goods_4.setLineWidth(1)
        self.goods_4.setMidLineWidth(0)
        self.goods_4.setObjectName("goods_4")
        self.gridLayout_4.addWidget(self.goods_4, 4, 0, 1, 1)
        self.dest_4 = QtWidgets.QLabel(self.widget)
        self.dest_4.setAutoFillBackground(False)
        self.dest_4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.dest_4.setFrameShape(QtWidgets.QFrame.Box)
        self.dest_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dest_4.setLineWidth(1)
        self.dest_4.setMidLineWidth(0)
        self.dest_4.setObjectName("dest_4")
        self.gridLayout_4.addWidget(self.dest_4, 1, 0, 1, 1)
        self.battery_4 = QtWidgets.QLabel(self.widget)
        self.battery_4.setAutoFillBackground(False)
        self.battery_4.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.battery_4.setFrameShape(QtWidgets.QFrame.Box)
        self.battery_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.battery_4.setLineWidth(1)
        self.battery_4.setMidLineWidth(0)
        self.battery_4.setObjectName("battery_4")
        self.gridLayout_4.addWidget(self.battery_4, 3, 0, 1, 1)
        self.carStart4 = QtWidgets.QLabel(self.widget)
        self.carStart4.setAutoFillBackground(False)
        self.carStart4.setStyleSheet("")
        self.carStart4.setFrameShape(QtWidgets.QFrame.Box)
        self.carStart4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carStart4.setLineWidth(1)
        self.carStart4.setMidLineWidth(0)
        self.carStart4.setObjectName("carStart4")
        self.gridLayout_4.addWidget(self.carStart4, 0, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.action_5 = QtWidgets.QLabel(self.widget)
        self.action_5.setAutoFillBackground(False)
        self.action_5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.action_5.setFrameShape(QtWidgets.QFrame.Box)
        self.action_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.action_5.setLineWidth(1)
        self.action_5.setMidLineWidth(0)
        self.action_5.setObjectName("action_5")
        self.gridLayout_5.addWidget(self.action_5, 2, 0, 1, 1)
        self.carFault5 = QtWidgets.QLabel(self.widget)
        self.carFault5.setAutoFillBackground(False)
        self.carFault5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carFault5.setFrameShape(QtWidgets.QFrame.Box)
        self.carFault5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carFault5.setLineWidth(1)
        self.carFault5.setMidLineWidth(0)
        self.carFault5.setObjectName("carFault5")
        self.gridLayout_5.addWidget(self.carFault5, 5, 1, 1, 1)
        self.carAction5 = QtWidgets.QLabel(self.widget)
        self.carAction5.setAutoFillBackground(False)
        self.carAction5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carAction5.setFrameShape(QtWidgets.QFrame.Box)
        self.carAction5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carAction5.setLineWidth(1)
        self.carAction5.setMidLineWidth(0)
        self.carAction5.setObjectName("carAction5")
        self.gridLayout_5.addWidget(self.carAction5, 2, 1, 1, 1)
        self.fault_5 = QtWidgets.QLabel(self.widget)
        self.fault_5.setAutoFillBackground(False)
        self.fault_5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.fault_5.setFrameShape(QtWidgets.QFrame.Box)
        self.fault_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fault_5.setLineWidth(1)
        self.fault_5.setMidLineWidth(0)
        self.fault_5.setObjectName("fault_5")
        self.gridLayout_5.addWidget(self.fault_5, 5, 0, 1, 1)
        self.carDest5 = QtWidgets.QLabel(self.widget)
        self.carDest5.setAutoFillBackground(False)
        self.carDest5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carDest5.setFrameShape(QtWidgets.QFrame.Box)
        self.carDest5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carDest5.setLineWidth(1)
        self.carDest5.setMidLineWidth(0)
        self.carDest5.setObjectName("carDest5")
        self.gridLayout_5.addWidget(self.carDest5, 1, 1, 1, 1)
        self.carGoods5 = QtWidgets.QLabel(self.widget)
        self.carGoods5.setAutoFillBackground(False)
        self.carGoods5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carGoods5.setFrameShape(QtWidgets.QFrame.Box)
        self.carGoods5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carGoods5.setLineWidth(1)
        self.carGoods5.setMidLineWidth(0)
        self.carGoods5.setObjectName("carGoods5")
        self.gridLayout_5.addWidget(self.carGoods5, 4, 1, 1, 1)
        self.start_5 = QtWidgets.QLabel(self.widget)
        self.start_5.setAutoFillBackground(False)
        self.start_5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.start_5.setFrameShape(QtWidgets.QFrame.Box)
        self.start_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.start_5.setLineWidth(1)
        self.start_5.setMidLineWidth(0)
        self.start_5.setObjectName("start_5")
        self.gridLayout_5.addWidget(self.start_5, 0, 0, 1, 1)
        self.carBattery5 = QtWidgets.QLabel(self.widget)
        self.carBattery5.setAutoFillBackground(False)
        self.carBattery5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carBattery5.setFrameShape(QtWidgets.QFrame.Box)
        self.carBattery5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carBattery5.setLineWidth(1)
        self.carBattery5.setMidLineWidth(0)
        self.carBattery5.setObjectName("carBattery5")
        self.gridLayout_5.addWidget(self.carBattery5, 3, 1, 1, 1)
        self.goods_5 = QtWidgets.QLabel(self.widget)
        self.goods_5.setAutoFillBackground(False)
        self.goods_5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.goods_5.setFrameShape(QtWidgets.QFrame.Box)
        self.goods_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.goods_5.setLineWidth(1)
        self.goods_5.setMidLineWidth(0)
        self.goods_5.setObjectName("goods_5")
        self.gridLayout_5.addWidget(self.goods_5, 4, 0, 1, 1)
        self.dest_5 = QtWidgets.QLabel(self.widget)
        self.dest_5.setAutoFillBackground(False)
        self.dest_5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.dest_5.setFrameShape(QtWidgets.QFrame.Box)
        self.dest_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dest_5.setLineWidth(1)
        self.dest_5.setMidLineWidth(0)
        self.dest_5.setObjectName("dest_5")
        self.gridLayout_5.addWidget(self.dest_5, 1, 0, 1, 1)
        self.battery_5 = QtWidgets.QLabel(self.widget)
        self.battery_5.setAutoFillBackground(False)
        self.battery_5.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.battery_5.setFrameShape(QtWidgets.QFrame.Box)
        self.battery_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.battery_5.setLineWidth(1)
        self.battery_5.setMidLineWidth(0)
        self.battery_5.setObjectName("battery_5")
        self.gridLayout_5.addWidget(self.battery_5, 3, 0, 1, 1)
        self.carStart5 = QtWidgets.QLabel(self.widget)
        self.carStart5.setAutoFillBackground(False)
        self.carStart5.setStyleSheet("")
        self.carStart5.setFrameShape(QtWidgets.QFrame.Box)
        self.carStart5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carStart5.setLineWidth(1)
        self.carStart5.setMidLineWidth(0)
        self.carStart5.setObjectName("carStart5")
        self.gridLayout_5.addWidget(self.carStart5, 0, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.action_6 = QtWidgets.QLabel(self.widget)
        self.action_6.setAutoFillBackground(False)
        self.action_6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.action_6.setFrameShape(QtWidgets.QFrame.Box)
        self.action_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.action_6.setLineWidth(1)
        self.action_6.setMidLineWidth(0)
        self.action_6.setObjectName("action_6")
        self.gridLayout_6.addWidget(self.action_6, 2, 0, 1, 1)
        self.carFault6 = QtWidgets.QLabel(self.widget)
        self.carFault6.setAutoFillBackground(False)
        self.carFault6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carFault6.setFrameShape(QtWidgets.QFrame.Box)
        self.carFault6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carFault6.setLineWidth(1)
        self.carFault6.setMidLineWidth(0)
        self.carFault6.setObjectName("carFault6")
        self.gridLayout_6.addWidget(self.carFault6, 5, 1, 1, 1)
        self.carAction6 = QtWidgets.QLabel(self.widget)
        self.carAction6.setAutoFillBackground(False)
        self.carAction6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carAction6.setFrameShape(QtWidgets.QFrame.Box)
        self.carAction6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carAction6.setLineWidth(1)
        self.carAction6.setMidLineWidth(0)
        self.carAction6.setObjectName("carAction6")
        self.gridLayout_6.addWidget(self.carAction6, 2, 1, 1, 1)
        self.fault_6 = QtWidgets.QLabel(self.widget)
        self.fault_6.setAutoFillBackground(False)
        self.fault_6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.fault_6.setFrameShape(QtWidgets.QFrame.Box)
        self.fault_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fault_6.setLineWidth(1)
        self.fault_6.setMidLineWidth(0)
        self.fault_6.setObjectName("fault_6")
        self.gridLayout_6.addWidget(self.fault_6, 5, 0, 1, 1)
        self.carDest6 = QtWidgets.QLabel(self.widget)
        self.carDest6.setAutoFillBackground(False)
        self.carDest6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carDest6.setFrameShape(QtWidgets.QFrame.Box)
        self.carDest6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carDest6.setLineWidth(1)
        self.carDest6.setMidLineWidth(0)
        self.carDest6.setObjectName("carDest6")
        self.gridLayout_6.addWidget(self.carDest6, 1, 1, 1, 1)
        self.carGoods6 = QtWidgets.QLabel(self.widget)
        self.carGoods6.setAutoFillBackground(False)
        self.carGoods6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carGoods6.setFrameShape(QtWidgets.QFrame.Box)
        self.carGoods6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carGoods6.setLineWidth(1)
        self.carGoods6.setMidLineWidth(0)
        self.carGoods6.setObjectName("carGoods6")
        self.gridLayout_6.addWidget(self.carGoods6, 4, 1, 1, 1)
        self.start_6 = QtWidgets.QLabel(self.widget)
        self.start_6.setAutoFillBackground(False)
        self.start_6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.start_6.setFrameShape(QtWidgets.QFrame.Box)
        self.start_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.start_6.setLineWidth(1)
        self.start_6.setMidLineWidth(0)
        self.start_6.setObjectName("start_6")
        self.gridLayout_6.addWidget(self.start_6, 0, 0, 1, 1)
        self.carBattery6 = QtWidgets.QLabel(self.widget)
        self.carBattery6.setAutoFillBackground(False)
        self.carBattery6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carBattery6.setFrameShape(QtWidgets.QFrame.Box)
        self.carBattery6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carBattery6.setLineWidth(1)
        self.carBattery6.setMidLineWidth(0)
        self.carBattery6.setObjectName("carBattery6")
        self.gridLayout_6.addWidget(self.carBattery6, 3, 1, 1, 1)
        self.goods_6 = QtWidgets.QLabel(self.widget)
        self.goods_6.setAutoFillBackground(False)
        self.goods_6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.goods_6.setFrameShape(QtWidgets.QFrame.Box)
        self.goods_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.goods_6.setLineWidth(1)
        self.goods_6.setMidLineWidth(0)
        self.goods_6.setObjectName("goods_6")
        self.gridLayout_6.addWidget(self.goods_6, 4, 0, 1, 1)
        self.dest_6 = QtWidgets.QLabel(self.widget)
        self.dest_6.setAutoFillBackground(False)
        self.dest_6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.dest_6.setFrameShape(QtWidgets.QFrame.Box)
        self.dest_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dest_6.setLineWidth(1)
        self.dest_6.setMidLineWidth(0)
        self.dest_6.setObjectName("dest_6")
        self.gridLayout_6.addWidget(self.dest_6, 1, 0, 1, 1)
        self.battery_6 = QtWidgets.QLabel(self.widget)
        self.battery_6.setAutoFillBackground(False)
        self.battery_6.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.battery_6.setFrameShape(QtWidgets.QFrame.Box)
        self.battery_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.battery_6.setLineWidth(1)
        self.battery_6.setMidLineWidth(0)
        self.battery_6.setObjectName("battery_6")
        self.gridLayout_6.addWidget(self.battery_6, 3, 0, 1, 1)
        self.carStart6 = QtWidgets.QLabel(self.widget)
        self.carStart6.setAutoFillBackground(False)
        self.carStart6.setStyleSheet("")
        self.carStart6.setFrameShape(QtWidgets.QFrame.Box)
        self.carStart6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carStart6.setLineWidth(1)
        self.carStart6.setMidLineWidth(0)
        self.carStart6.setObjectName("carStart6")
        self.gridLayout_6.addWidget(self.carStart6, 0, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_6)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_7.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.action_7 = QtWidgets.QLabel(self.widget)
        self.action_7.setAutoFillBackground(False)
        self.action_7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.action_7.setFrameShape(QtWidgets.QFrame.Box)
        self.action_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.action_7.setLineWidth(1)
        self.action_7.setMidLineWidth(0)
        self.action_7.setObjectName("action_7")
        self.gridLayout_7.addWidget(self.action_7, 2, 0, 1, 1)
        self.carFault7 = QtWidgets.QLabel(self.widget)
        self.carFault7.setAutoFillBackground(False)
        self.carFault7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carFault7.setFrameShape(QtWidgets.QFrame.Box)
        self.carFault7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carFault7.setLineWidth(1)
        self.carFault7.setMidLineWidth(0)
        self.carFault7.setObjectName("carFault7")
        self.gridLayout_7.addWidget(self.carFault7, 5, 1, 1, 1)
        self.carAction7 = QtWidgets.QLabel(self.widget)
        self.carAction7.setAutoFillBackground(False)
        self.carAction7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carAction7.setFrameShape(QtWidgets.QFrame.Box)
        self.carAction7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carAction7.setLineWidth(1)
        self.carAction7.setMidLineWidth(0)
        self.carAction7.setObjectName("carAction7")
        self.gridLayout_7.addWidget(self.carAction7, 2, 1, 1, 1)
        self.fault_7 = QtWidgets.QLabel(self.widget)
        self.fault_7.setAutoFillBackground(False)
        self.fault_7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.fault_7.setFrameShape(QtWidgets.QFrame.Box)
        self.fault_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fault_7.setLineWidth(1)
        self.fault_7.setMidLineWidth(0)
        self.fault_7.setObjectName("fault_7")
        self.gridLayout_7.addWidget(self.fault_7, 5, 0, 1, 1)
        self.carDest7 = QtWidgets.QLabel(self.widget)
        self.carDest7.setAutoFillBackground(False)
        self.carDest7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carDest7.setFrameShape(QtWidgets.QFrame.Box)
        self.carDest7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carDest7.setLineWidth(1)
        self.carDest7.setMidLineWidth(0)
        self.carDest7.setObjectName("carDest7")
        self.gridLayout_7.addWidget(self.carDest7, 1, 1, 1, 1)
        self.carGoods7 = QtWidgets.QLabel(self.widget)
        self.carGoods7.setAutoFillBackground(False)
        self.carGoods7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carGoods7.setFrameShape(QtWidgets.QFrame.Box)
        self.carGoods7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carGoods7.setLineWidth(1)
        self.carGoods7.setMidLineWidth(0)
        self.carGoods7.setObjectName("carGoods7")
        self.gridLayout_7.addWidget(self.carGoods7, 4, 1, 1, 1)
        self.start_7 = QtWidgets.QLabel(self.widget)
        self.start_7.setAutoFillBackground(False)
        self.start_7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.start_7.setFrameShape(QtWidgets.QFrame.Box)
        self.start_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.start_7.setLineWidth(1)
        self.start_7.setMidLineWidth(0)
        self.start_7.setObjectName("start_7")
        self.gridLayout_7.addWidget(self.start_7, 0, 0, 1, 1)
        self.carBattery7 = QtWidgets.QLabel(self.widget)
        self.carBattery7.setAutoFillBackground(False)
        self.carBattery7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carBattery7.setFrameShape(QtWidgets.QFrame.Box)
        self.carBattery7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carBattery7.setLineWidth(1)
        self.carBattery7.setMidLineWidth(0)
        self.carBattery7.setObjectName("carBattery7")
        self.gridLayout_7.addWidget(self.carBattery7, 3, 1, 1, 1)
        self.goods_7 = QtWidgets.QLabel(self.widget)
        self.goods_7.setAutoFillBackground(False)
        self.goods_7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.goods_7.setFrameShape(QtWidgets.QFrame.Box)
        self.goods_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.goods_7.setLineWidth(1)
        self.goods_7.setMidLineWidth(0)
        self.goods_7.setObjectName("goods_7")
        self.gridLayout_7.addWidget(self.goods_7, 4, 0, 1, 1)
        self.dest_7 = QtWidgets.QLabel(self.widget)
        self.dest_7.setAutoFillBackground(False)
        self.dest_7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.dest_7.setFrameShape(QtWidgets.QFrame.Box)
        self.dest_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dest_7.setLineWidth(1)
        self.dest_7.setMidLineWidth(0)
        self.dest_7.setObjectName("dest_7")
        self.gridLayout_7.addWidget(self.dest_7, 1, 0, 1, 1)
        self.battery_7 = QtWidgets.QLabel(self.widget)
        self.battery_7.setAutoFillBackground(False)
        self.battery_7.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.battery_7.setFrameShape(QtWidgets.QFrame.Box)
        self.battery_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.battery_7.setLineWidth(1)
        self.battery_7.setMidLineWidth(0)
        self.battery_7.setObjectName("battery_7")
        self.gridLayout_7.addWidget(self.battery_7, 3, 0, 1, 1)
        self.carStart7 = QtWidgets.QLabel(self.widget)
        self.carStart7.setAutoFillBackground(False)
        self.carStart7.setStyleSheet("")
        self.carStart7.setFrameShape(QtWidgets.QFrame.Box)
        self.carStart7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carStart7.setLineWidth(1)
        self.carStart7.setMidLineWidth(0)
        self.carStart7.setObjectName("carStart7")
        self.gridLayout_7.addWidget(self.carStart7, 0, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_7.setColumnStretch(1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_7)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_8.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.action_8 = QtWidgets.QLabel(self.widget)
        self.action_8.setAutoFillBackground(False)
        self.action_8.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.action_8.setFrameShape(QtWidgets.QFrame.Box)
        self.action_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.action_8.setLineWidth(1)
        self.action_8.setMidLineWidth(0)
        self.action_8.setObjectName("action_8")
        self.gridLayout_8.addWidget(self.action_8, 2, 0, 1, 1)
        self.carFault8 = QtWidgets.QLabel(self.widget)
        self.carFault8.setAutoFillBackground(False)
        self.carFault8.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carFault8.setFrameShape(QtWidgets.QFrame.Box)
        self.carFault8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carFault8.setLineWidth(1)
        self.carFault8.setMidLineWidth(0)
        self.carFault8.setObjectName("carFault8")
        self.gridLayout_8.addWidget(self.carFault8, 5, 1, 1, 1)
        self.carAction8 = QtWidgets.QLabel(self.widget)
        self.carAction8.setAutoFillBackground(False)
        self.carAction8.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carAction8.setFrameShape(QtWidgets.QFrame.Box)
        self.carAction8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carAction8.setLineWidth(1)
        self.carAction8.setMidLineWidth(0)
        self.carAction8.setObjectName("carAction8")
        self.gridLayout_8.addWidget(self.carAction8, 2, 1, 1, 1)
        self.fault_8 = QtWidgets.QLabel(self.widget)
        self.fault_8.setAutoFillBackground(False)
        self.fault_8.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.fault_8.setFrameShape(QtWidgets.QFrame.Box)
        self.fault_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fault_8.setLineWidth(1)
        self.fault_8.setMidLineWidth(0)
        self.fault_8.setObjectName("fault_8")
        self.gridLayout_8.addWidget(self.fault_8, 5, 0, 1, 1)
        self.carDest8 = QtWidgets.QLabel(self.widget)
        self.carDest8.setAutoFillBackground(False)
        self.carDest8.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carDest8.setFrameShape(QtWidgets.QFrame.Box)
        self.carDest8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carDest8.setLineWidth(1)
        self.carDest8.setMidLineWidth(0)
        self.carDest8.setObjectName("carDest8")
        self.gridLayout_8.addWidget(self.carDest8, 1, 1, 1, 1)
        self.carGoods8 = QtWidgets.QLabel(self.widget)
        self.carGoods8.setAutoFillBackground(False)
        self.carGoods8.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carGoods8.setFrameShape(QtWidgets.QFrame.Box)
        self.carGoods8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carGoods8.setLineWidth(1)
        self.carGoods8.setMidLineWidth(0)
        self.carGoods8.setObjectName("carGoods8")
        self.gridLayout_8.addWidget(self.carGoods8, 4, 1, 1, 1)
        self.start_8 = QtWidgets.QLabel(self.widget)
        self.start_8.setAutoFillBackground(False)
        self.start_8.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.start_8.setFrameShape(QtWidgets.QFrame.Box)
        self.start_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.start_8.setLineWidth(1)
        self.start_8.setMidLineWidth(0)
        self.start_8.setObjectName("start_8")
        self.gridLayout_8.addWidget(self.start_8, 0, 0, 1, 1)
        self.carBattery8 = QtWidgets.QLabel(self.widget)
        self.carBattery8.setAutoFillBackground(False)
        self.carBattery8.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carBattery8.setFrameShape(QtWidgets.QFrame.Box)
        self.carBattery8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carBattery8.setLineWidth(1)
        self.carBattery8.setMidLineWidth(0)
        self.carBattery8.setObjectName("carBattery8")
        self.gridLayout_8.addWidget(self.carBattery8, 3, 1, 1, 1)
        self.goods_8 = QtWidgets.QLabel(self.widget)
        self.goods_8.setAutoFillBackground(False)
        self.goods_8.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.goods_8.setFrameShape(QtWidgets.QFrame.Box)
        self.goods_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.goods_8.setLineWidth(1)
        self.goods_8.setMidLineWidth(0)
        self.goods_8.setObjectName("goods_8")
        self.gridLayout_8.addWidget(self.goods_8, 4, 0, 1, 1)
        self.dest_8 = QtWidgets.QLabel(self.widget)
        self.dest_8.setAutoFillBackground(False)
        self.dest_8.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.dest_8.setFrameShape(QtWidgets.QFrame.Box)
        self.dest_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dest_8.setLineWidth(1)
        self.dest_8.setMidLineWidth(0)
        self.dest_8.setObjectName("dest_8")
        self.gridLayout_8.addWidget(self.dest_8, 1, 0, 1, 1)
        self.battery_8 = QtWidgets.QLabel(self.widget)
        self.battery_8.setAutoFillBackground(False)
        self.battery_8.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.battery_8.setFrameShape(QtWidgets.QFrame.Box)
        self.battery_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.battery_8.setLineWidth(1)
        self.battery_8.setMidLineWidth(0)
        self.battery_8.setObjectName("battery_8")
        self.gridLayout_8.addWidget(self.battery_8, 3, 0, 1, 1)
        self.carStart8 = QtWidgets.QLabel(self.widget)
        self.carStart8.setAutoFillBackground(False)
        self.carStart8.setStyleSheet("")
        self.carStart8.setFrameShape(QtWidgets.QFrame.Box)
        self.carStart8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carStart8.setLineWidth(1)
        self.carStart8.setMidLineWidth(0)
        self.carStart8.setObjectName("carStart8")
        self.gridLayout_8.addWidget(self.carStart8, 0, 1, 1, 1)
        self.gridLayout_8.setColumnStretch(0, 1)
        self.gridLayout_8.setColumnStretch(1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_8)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_9.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.action_9 = QtWidgets.QLabel(self.widget)
        self.action_9.setAutoFillBackground(False)
        self.action_9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.action_9.setFrameShape(QtWidgets.QFrame.Box)
        self.action_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.action_9.setLineWidth(1)
        self.action_9.setMidLineWidth(0)
        self.action_9.setObjectName("action_9")
        self.gridLayout_9.addWidget(self.action_9, 2, 0, 1, 1)
        self.carFault9 = QtWidgets.QLabel(self.widget)
        self.carFault9.setAutoFillBackground(False)
        self.carFault9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carFault9.setFrameShape(QtWidgets.QFrame.Box)
        self.carFault9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carFault9.setLineWidth(1)
        self.carFault9.setMidLineWidth(0)
        self.carFault9.setObjectName("carFault9")
        self.gridLayout_9.addWidget(self.carFault9, 5, 1, 1, 1)
        self.carAction9 = QtWidgets.QLabel(self.widget)
        self.carAction9.setAutoFillBackground(False)
        self.carAction9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carAction9.setFrameShape(QtWidgets.QFrame.Box)
        self.carAction9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carAction9.setLineWidth(1)
        self.carAction9.setMidLineWidth(0)
        self.carAction9.setObjectName("carAction9")
        self.gridLayout_9.addWidget(self.carAction9, 2, 1, 1, 1)
        self.fault_9 = QtWidgets.QLabel(self.widget)
        self.fault_9.setAutoFillBackground(False)
        self.fault_9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.fault_9.setFrameShape(QtWidgets.QFrame.Box)
        self.fault_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fault_9.setLineWidth(1)
        self.fault_9.setMidLineWidth(0)
        self.fault_9.setObjectName("fault_9")
        self.gridLayout_9.addWidget(self.fault_9, 5, 0, 1, 1)
        self.carDest9 = QtWidgets.QLabel(self.widget)
        self.carDest9.setAutoFillBackground(False)
        self.carDest9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carDest9.setFrameShape(QtWidgets.QFrame.Box)
        self.carDest9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carDest9.setLineWidth(1)
        self.carDest9.setMidLineWidth(0)
        self.carDest9.setObjectName("carDest9")
        self.gridLayout_9.addWidget(self.carDest9, 1, 1, 1, 1)
        self.carGoods9 = QtWidgets.QLabel(self.widget)
        self.carGoods9.setAutoFillBackground(False)
        self.carGoods9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carGoods9.setFrameShape(QtWidgets.QFrame.Box)
        self.carGoods9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carGoods9.setLineWidth(1)
        self.carGoods9.setMidLineWidth(0)
        self.carGoods9.setObjectName("carGoods9")
        self.gridLayout_9.addWidget(self.carGoods9, 4, 1, 1, 1)
        self.start_9 = QtWidgets.QLabel(self.widget)
        self.start_9.setAutoFillBackground(False)
        self.start_9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.start_9.setFrameShape(QtWidgets.QFrame.Box)
        self.start_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.start_9.setLineWidth(1)
        self.start_9.setMidLineWidth(0)
        self.start_9.setObjectName("start_9")
        self.gridLayout_9.addWidget(self.start_9, 0, 0, 1, 1)
        self.carBattery9 = QtWidgets.QLabel(self.widget)
        self.carBattery9.setAutoFillBackground(False)
        self.carBattery9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.carBattery9.setFrameShape(QtWidgets.QFrame.Box)
        self.carBattery9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carBattery9.setLineWidth(1)
        self.carBattery9.setMidLineWidth(0)
        self.carBattery9.setObjectName("carBattery9")
        self.gridLayout_9.addWidget(self.carBattery9, 3, 1, 1, 1)
        self.goods_9 = QtWidgets.QLabel(self.widget)
        self.goods_9.setAutoFillBackground(False)
        self.goods_9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.goods_9.setFrameShape(QtWidgets.QFrame.Box)
        self.goods_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.goods_9.setLineWidth(1)
        self.goods_9.setMidLineWidth(0)
        self.goods_9.setObjectName("goods_9")
        self.gridLayout_9.addWidget(self.goods_9, 4, 0, 1, 1)
        self.dest_9 = QtWidgets.QLabel(self.widget)
        self.dest_9.setAutoFillBackground(False)
        self.dest_9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.dest_9.setFrameShape(QtWidgets.QFrame.Box)
        self.dest_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dest_9.setLineWidth(1)
        self.dest_9.setMidLineWidth(0)
        self.dest_9.setObjectName("dest_9")
        self.gridLayout_9.addWidget(self.dest_9, 1, 0, 1, 1)
        self.battery_9 = QtWidgets.QLabel(self.widget)
        self.battery_9.setAutoFillBackground(False)
        self.battery_9.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.battery_9.setFrameShape(QtWidgets.QFrame.Box)
        self.battery_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.battery_9.setLineWidth(1)
        self.battery_9.setMidLineWidth(0)
        self.battery_9.setObjectName("battery_9")
        self.gridLayout_9.addWidget(self.battery_9, 3, 0, 1, 1)
        self.carStart9 = QtWidgets.QLabel(self.widget)
        self.carStart9.setAutoFillBackground(False)
        self.carStart9.setStyleSheet("")
        self.carStart9.setFrameShape(QtWidgets.QFrame.Box)
        self.carStart9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.carStart9.setLineWidth(1)
        self.carStart9.setMidLineWidth(0)
        self.carStart9.setObjectName("carStart9")
        self.gridLayout_9.addWidget(self.carStart9, 0, 1, 1, 1)
        self.gridLayout_9.setColumnStretch(0, 1)
        self.gridLayout_9.setColumnStretch(1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)

        # 用于显示时间的label
        self.timeshow = QtWidgets.QLabel(self.centralwidget)
        self.timeshow.setGeometry(QtCore.QRect(MainWindow.size().width() * 0.7, 0, MainWindow.size().width() * 0.3, 60))
        self.timeshow.setStyleSheet("font: 20pt \"微软雅黑 \";font-weight:bold;""color: rgb(255, 255, 255);")
        timer = QTimer(self)
        timer.timeout.connect(self.showtime)
        timer.start()

        pix = QPixmap('xio.jpg')
        self.picture = QtWidgets.QLabel(self.centralwidget)
        self.picture.setGeometry(QtCore.QRect(00, 0, 300, 60))
        self.picture.setPixmap(pix)
        self.picture.setScaledContents(True)
        # 用于显示标题的label
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(0, 0, MainWindow.size().width(), 60))
        self.label1.setText("杭州西奥AGV小车流动看板")
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.label1.setStyleSheet("font: 34pt \"微软雅黑\";\n"
                                  "background-color: rgb(0, 128, 255);\n"
                                  "color: rgb(255, 255, 255);")

        self.label1.raise_()
        self.picture.raise_()
        self.timeshow.raise_()
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        # self.menubar.setStyleSheet("background-color: rgb(255, 255, 250);\n"
        #                            "selection-background-color: rgb(100, 100, 100);\n"
        #                            "color: rgb(0, 0, 0);")
        # self.menu = QtWidgets.QMenu(self.menubar)
        # self.menu.setObjectName("menu")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        # self.fullScreen = QtWidgets.QAction(MainWindow)
        # self.fullScreen.setObjectName("fullScreen")
        # self.exitFullScreen = QtWidgets.QAction(MainWindow)
        # self.exitFullScreen.setObjectName("exitFullScreen")
        # self.menu.addAction(self.fullScreen)
        # self.menu.addAction(self.exitFullScreen)
        # self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.initUI()
        self.createContextMenu()


    def createContextMenu(self):
        '''''
        创建右键菜单
        '''
        # 必须将ContextMenuPolicy设置为Qt.CustomContextMenu
        # 否则无法使用customContextMenuRequested信号
        self.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.customContextMenuRequested.connect(self.showContextMenu)

        # 创建QMenu
        self.contextMenu = QtWidgets.QMenu(self)
        self.actionA = self.contextMenu.addAction(u'全屏模式')
        self.actionB = self.contextMenu.addAction(u'退出全屏')
        # 将动作与处理函数相关联
        # 这里为了简单，将所有action与同一个处理函数相关联，
        # 当然也可以将他们分别与不同函数关联，实现不同的功能
        self.actionA.triggered.connect(self.showFullScreen)
        self.actionB.triggered.connect(self.showNormal)

    def showContextMenu(self, pos):
        '''''
        右键点击时调用的函数
        '''
        # 菜单显示前，将它移动到鼠标点击的位置
        self.contextMenu.move(QtGui.QCursor().pos())
        self.contextMenu.show()


    def showtime(self):
        datetime = QDateTime.currentDateTime()
        text = datetime.toString("yyyy-MM-dd hh:mm:ss")
        self.timeshow.setText(text)

    def initUI(self):
        self.backend = BackendThread()
        self.backend.update_data.connect(self.handleDisplay)
        self.backend.start()

    def handleDisplay(self, data):
        self.label.data = data
        # self.label.setText(str(data[2]))
        for i in range(1, 10):
            # var1 = 'carState' + str(i)
            # getattr(self, 'carState' + str(i)).setText(str(data[1]))
            # getattr(self, 'carStart' + str(i)).setText(str(data[2]))
            # getattr(self, 'carEnd' + str(i)).setText(str(data[3]))
            # getattr(self, 'carDest' + str(i)).setText(str(data[4]))
            # getattr(self, 'carProgress' + str(i)).setText(str(data[5]))
            # getattr(self, 'carAction' + str(i)).setText(str(data[6]))
            # getattr(self, 'carGoods' + str(i)).setText(str(data[7]))
            # getattr(self, 'carBattery' + str(i)).setText(str(data[8]))
            # getattr(self, 'carFault' + str(i)).setText(str(data[9]))

            # getattr(self, 'carState' + str(i)).setText(str(data['carState' + str(i)]))
            getattr(self, 'carStart' + str(i)).setText(str(data['carStart' + str(i)]))
            # getattr(self, 'carEnd' + str(i)).setText(str(data['carEnd' + str(i)]))
            getattr(self, 'carDest' + str(i)).setText(str(data['carDest' + str(i)]))
            # getattr(self, 'carProgress' + str(i)).setText(str(data['carProgress' + str(i)]))
            getattr(self, 'carAction' + str(i)).setText(str(data['carAction' + str(i)]))
            getattr(self, 'carGoods' + str(i)).setText(str(data['carGoods' + str(i)]))
            getattr(self, 'carBattery' + str(i)).setText(str(data['carBattery' + str(i)]))
            getattr(self, 'carFault' + str(i)).setText(str(data['carFault' + str(i)]))

            # 重绘
        self.label.repaint()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.action.setText(_translate("MainWindow", "动作"))
        self.carFault1.setText(_translate("MainWindow", "发现障碍"))
        self.carAction1.setText(_translate("MainWindow", "取货"))
        self.fault.setText(_translate("MainWindow", "故障"))
        self.carDest1.setText(_translate("MainWindow", "200"))
        self.carGoods1.setText(_translate("MainWindow", "有货"))
        self.start.setText(_translate("MainWindow", "当前点"))
        self.carBattery1.setText(_translate("MainWindow", "正常"))
        self.goods.setText(_translate("MainWindow", "货物"))
        self.dest.setText(_translate("MainWindow", "终点"))
        self.battery.setText(_translate("MainWindow", "电池"))
        self.carStart1.setText(_translate("MainWindow", "99"))
        self.action_2.setText(_translate("MainWindow", "动作"))
        self.carFault2.setText(_translate("MainWindow", "无故障"))
        self.carAction2.setText(_translate("MainWindow", "取货"))
        self.fault_2.setText(_translate("MainWindow", "故障"))
        self.carDest2.setText(_translate("MainWindow", "389"))
        self.carGoods2.setText(_translate("MainWindow", "有货"))
        self.start_2.setText(_translate("MainWindow", "当前点"))
        self.carBattery2.setText(_translate("MainWindow", "正常"))
        self.goods_2.setText(_translate("MainWindow", "货物"))
        self.dest_2.setText(_translate("MainWindow", "终点"))
        self.battery_2.setText(_translate("MainWindow", "电池"))
        self.carStart2.setText(_translate("MainWindow", "386"))
        self.action_3.setText(_translate("MainWindow", "动作"))
        self.carFault3.setText(_translate("MainWindow", "无故障"))
        self.carAction3.setText(_translate("MainWindow", "取货"))
        self.fault_3.setText(_translate("MainWindow", "故障"))
        self.carDest3.setText(_translate("MainWindow", "588"))
        self.carGoods3.setText(_translate("MainWindow", "有货"))
        self.start_3.setText(_translate("MainWindow", "当前点"))
        self.carBattery3.setText(_translate("MainWindow", "正常"))
        self.goods_3.setText(_translate("MainWindow", "货物"))
        self.dest_3.setText(_translate("MainWindow", "终点"))
        self.battery_3.setText(_translate("MainWindow", "电池"))
        self.carStart3.setText(_translate("MainWindow", "586"))
        self.action_4.setText(_translate("MainWindow", "动作"))
        self.carFault4.setText(_translate("MainWindow", "无故障"))
        self.carAction4.setText(_translate("MainWindow", "取货"))
        self.fault_4.setText(_translate("MainWindow", "故障"))
        self.carDest4.setText(_translate("MainWindow", "281"))
        self.carGoods4.setText(_translate("MainWindow", "有货"))
        self.start_4.setText(_translate("MainWindow", "当前点"))
        self.carBattery4.setText(_translate("MainWindow", "正常"))
        self.goods_4.setText(_translate("MainWindow", "货物"))
        self.dest_4.setText(_translate("MainWindow", "终点"))
        self.battery_4.setText(_translate("MainWindow", "电池"))
        self.carStart4.setText(_translate("MainWindow", "261"))
        self.action_5.setText(_translate("MainWindow", "动作"))
        self.carFault5.setText(_translate("MainWindow", "无故障"))
        self.carAction5.setText(_translate("MainWindow", "送货"))
        self.fault_5.setText(_translate("MainWindow", "故障"))
        self.carDest5.setText(_translate("MainWindow", "891"))
        self.carGoods5.setText(_translate("MainWindow", "有货"))
        self.start_5.setText(_translate("MainWindow", "当前点"))
        self.carBattery5.setText(_translate("MainWindow", "正常"))
        self.goods_5.setText(_translate("MainWindow", "货物"))
        self.dest_5.setText(_translate("MainWindow", "终点"))
        self.battery_5.setText(_translate("MainWindow", "电池"))
        self.carStart5.setText(_translate("MainWindow", "899"))
        self.action_6.setText(_translate("MainWindow", "动作"))
        self.carFault6.setText(_translate("MainWindow", "从等待状态退出"))
        self.carAction6.setText(_translate("MainWindow", "送货"))
        self.fault_6.setText(_translate("MainWindow", "故障"))
        self.carDest6.setText(_translate("MainWindow", "143"))
        self.carGoods6.setText(_translate("MainWindow", "有货"))
        self.start_6.setText(_translate("MainWindow", "当前点"))
        self.carBattery6.setText(_translate("MainWindow", "正常"))
        self.goods_6.setText(_translate("MainWindow", "货物"))
        self.dest_6.setText(_translate("MainWindow", "终点"))
        self.battery_6.setText(_translate("MainWindow", "电池"))
        self.carStart6.setText(_translate("MainWindow", "141"))
        self.action_7.setText(_translate("MainWindow", "动作"))
        self.carFault7.setText(_translate("MainWindow", "无故障"))
        self.carAction7.setText(_translate("MainWindow", "送货"))
        self.fault_7.setText(_translate("MainWindow", "故障"))
        self.carDest7.setText(_translate("MainWindow", "274"))
        self.carGoods7.setText(_translate("MainWindow", "有货"))
        self.start_7.setText(_translate("MainWindow", "当前点"))
        self.carBattery7.setText(_translate("MainWindow", "正常"))
        self.goods_7.setText(_translate("MainWindow", "货物"))
        self.dest_7.setText(_translate("MainWindow", "终点"))
        self.battery_7.setText(_translate("MainWindow", "电池"))
        self.carStart7.setText(_translate("MainWindow", "272"))
        self.action_8.setText(_translate("MainWindow", "动作"))
        self.carFault8.setText(_translate("MainWindow", "MCU的CAN通讯中断"))
        self.carAction8.setText(_translate("MainWindow", "二期取货"))
        self.fault_8.setText(_translate("MainWindow", "故障"))
        self.carDest8.setText(_translate("MainWindow", "336"))
        self.carGoods8.setText(_translate("MainWindow", "有货"))
        self.start_8.setText(_translate("MainWindow", "当前点"))
        self.carBattery8.setText(_translate("MainWindow", "正常"))
        self.goods_8.setText(_translate("MainWindow", "货物"))
        self.dest_8.setText(_translate("MainWindow", "终点"))
        self.battery_8.setText(_translate("MainWindow", "电池"))
        self.carStart8.setText(_translate("MainWindow", "334"))
        self.action_9.setText(_translate("MainWindow", "动作"))
        self.carFault9.setText(_translate("MainWindow", "无故障"))
        self.carAction9.setText(_translate("MainWindow", "二期取货"))
        self.fault_9.setText(_translate("MainWindow", "故障"))
        self.carDest9.setText(_translate("MainWindow", "568"))
        self.carGoods9.setText(_translate("MainWindow", "有货"))
        self.start_9.setText(_translate("MainWindow", "当前点"))
        self.carBattery9.setText(_translate("MainWindow", "正常"))
        self.goods_9.setText(_translate("MainWindow", "货物"))
        self.dest_9.setText(_translate("MainWindow", "终点"))
        self.battery_9.setText(_translate("MainWindow", "电池"))
        self.carStart9.setText(_translate("MainWindow", "566"))

        # self.menu.setTitle(_translate("mainwindow", "显示"))
        # self.fullScreen.setText(_translate("mainwindow", "全屏模式 "))
        # self.exitFullScreen.setText(_translate("mainwindow", "退出全屏"))
