# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cps_model.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 801, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 481, 541))
        self.label.setStyleSheet("image: url(:/newPrefix/images/3.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(580, 50, 171, 501))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(42)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(25, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(26, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(27, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(28, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(29, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(30, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(31, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(32, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(33, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(34, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(35, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(36, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(37, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(38, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(39, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(40, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(41, 0, item)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 801, 531))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/images/1.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.tableWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_T = QtWidgets.QMenu(self.menubar)
        self.menu_T.setObjectName("menu_T")
        self.menu_W = QtWidgets.QMenu(self.menubar)
        self.menu_W.setObjectName("menu_W")
        self.menu_S = QtWidgets.QMenu(self.menubar)
        self.menu_S.setObjectName("menu_S")
        self.menu_R = QtWidgets.QMenu(self.menubar)
        self.menu_R.setObjectName("menu_R")
        self.menu_V = QtWidgets.QMenu(self.menubar)
        self.menu_V.setObjectName("menu_V")
        self.menu_A = QtWidgets.QMenu(self.menubar)
        self.menu_A.setObjectName("menu_A")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_T.menuAction())
        self.menubar.addAction(self.menu_W.menuAction())
        self.menubar.addAction(self.menu_S.menuAction())
        self.menubar.addAction(self.menu_R.menuAction())
        self.menubar.addAction(self.menu_V.menuAction())
        self.menubar.addAction(self.menu_A.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPS生产线的面向对象广义随机Petri网模型"))
        self.label_3.setText(_translate("MainWindow", "杭州西奥电梯有限公司 厚板生产线 面向对象随机Petri网模型"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "P0"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "P1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "P2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "P3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "P4"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "P5"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "P6"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "P7"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "P8"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "P9"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "P10"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "P11"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "P12"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "P13"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "P14"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "IM1-1"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "IM1-2"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "IM2"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "IM3"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "OM1"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "OM2"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "OM3-1"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "OM3-2"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "T0"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "T1"))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("MainWindow", "T2"))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("MainWindow", "T3"))
        item = self.tableWidget.verticalHeaderItem(27)
        item.setText(_translate("MainWindow", "T4"))
        item = self.tableWidget.verticalHeaderItem(28)
        item.setText(_translate("MainWindow", "T5"))
        item = self.tableWidget.verticalHeaderItem(29)
        item.setText(_translate("MainWindow", "T6"))
        item = self.tableWidget.verticalHeaderItem(30)
        item.setText(_translate("MainWindow", "T7"))
        item = self.tableWidget.verticalHeaderItem(31)
        item.setText(_translate("MainWindow", "T8"))
        item = self.tableWidget.verticalHeaderItem(32)
        item.setText(_translate("MainWindow", "T9"))
        item = self.tableWidget.verticalHeaderItem(33)
        item.setText(_translate("MainWindow", "T10"))
        item = self.tableWidget.verticalHeaderItem(34)
        item.setText(_translate("MainWindow", "T11"))
        item = self.tableWidget.verticalHeaderItem(35)
        item.setText(_translate("MainWindow", "T12"))
        item = self.tableWidget.verticalHeaderItem(36)
        item.setText(_translate("MainWindow", "T13"))
        item = self.tableWidget.verticalHeaderItem(37)
        item.setText(_translate("MainWindow", "T14"))
        item = self.tableWidget.verticalHeaderItem(38)
        item.setText(_translate("MainWindow", "g12"))
        item = self.tableWidget.verticalHeaderItem(39)
        item.setText(_translate("MainWindow", "g23"))
        item = self.tableWidget.verticalHeaderItem(40)
        item.setText(_translate("MainWindow", "g31-1"))
        item = self.tableWidget.verticalHeaderItem(41)
        item.setText(_translate("MainWindow", "g31-2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "含义"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "板材A等待打孔"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "冲床与机器人可用"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "板材A打孔中"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "板材B等待折弯"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "板材A等待折弯"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "板材B折弯中"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "PPEB-220T与机器人可用"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "板材A折弯中"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "码垛机器人可用"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "板材A、B码垛中"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "板材B角度校准中"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "PPEC-220T与机器人可用"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("MainWindow", "板材A等待码垛"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("MainWindow", "板材B等待码垛"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("MainWindow", "板材B角度判定结果"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("MainWindow", "板材B角度合格信息"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("MainWindow", "板材B角度不合格信息"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("MainWindow", "板材B等待角度检测"))
        item = self.tableWidget.item(18, 0)
        item.setText(_translate("MainWindow", "板材B等待角度判定"))
        item = self.tableWidget.item(19, 0)
        item.setText(_translate("MainWindow", "板材B角度检测请求"))
        item = self.tableWidget.item(20, 0)
        item.setText(_translate("MainWindow", "板材B角度信息"))
        item = self.tableWidget.item(21, 0)
        item.setText(_translate("MainWindow", "板材B角度合格信息"))
        item = self.tableWidget.item(22, 0)
        item.setText(_translate("MainWindow", "板材B角度不合格信息"))
        item = self.tableWidget.item(23, 0)
        item.setText(_translate("MainWindow", "板材A打孔开始"))
        item = self.tableWidget.item(24, 0)
        item.setText(_translate("MainWindow", "板材A打孔结束"))
        item = self.tableWidget.item(25, 0)
        item.setText(_translate("MainWindow", "板材B折弯开始"))
        item = self.tableWidget.item(26, 0)
        item.setText(_translate("MainWindow", "板材A折弯开始"))
        item = self.tableWidget.item(27, 0)
        item.setText(_translate("MainWindow", "板材A、B码垛结束"))
        item = self.tableWidget.item(28, 0)
        item.setText(_translate("MainWindow", "板材B角度校准结束"))
        item = self.tableWidget.item(29, 0)
        item.setText(_translate("MainWindow", "板材B折弯结束"))
        item = self.tableWidget.item(30, 0)
        item.setText(_translate("MainWindow", "板材A折弯结束"))
        item = self.tableWidget.item(31, 0)
        item.setText(_translate("MainWindow", "板材A、B码垛开始"))
        item = self.tableWidget.item(32, 0)
        item.setText(_translate("MainWindow", "板材B角度判定合格"))
        item = self.tableWidget.item(33, 0)
        item.setText(_translate("MainWindow", "板材B角度不合格，开始校准"))
        item = self.tableWidget.item(34, 0)
        item.setText(_translate("MainWindow", "板材B角度检测"))
        item = self.tableWidget.item(35, 0)
        item.setText(_translate("MainWindow", "板材B角度为合格"))
        item = self.tableWidget.item(36, 0)
        item.setText(_translate("MainWindow", "板材B角度为不合格"))
        item = self.tableWidget.item(37, 0)
        item.setText(_translate("MainWindow", "板材B角度判定"))
        item = self.tableWidget.item(38, 0)
        item.setText(_translate("MainWindow", "Ob1与Ob2之间的门变迁"))
        item = self.tableWidget.item(39, 0)
        item.setText(_translate("MainWindow", "Ob2与Ob3之间的门变迁"))
        item = self.tableWidget.item(40, 0)
        item.setText(_translate("MainWindow", "Ob3与Ob1之间的门变迁1"))
        item = self.tableWidget.item(41, 0)
        item.setText(_translate("MainWindow", "Ob3与Ob1之间的门变迁2"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.menu_F.setTitle(_translate("MainWindow", "文件(F)"))
        self.menu_T.setTitle(_translate("MainWindow", "工具(T)"))
        self.menu_W.setTitle(_translate("MainWindow", "窗口(W)"))
        self.menu_S.setTitle(_translate("MainWindow", "设置(S)"))
        self.menu_R.setTitle(_translate("MainWindow", "运行(R)"))
        self.menu_V.setTitle(_translate("MainWindow", "查看(V)"))
        self.menu_A.setTitle(_translate("MainWindow", "分析(A)"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助(H)"))


import resource_rc
